version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: student-db
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student123
    ports:
      - "5460:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d studentdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: student-app
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentdb
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: student123
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
